MedicExpermed/Models/Consultation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace MedicExpermed.Models
{
    public class Consultation
    {
        public int Id { get; set; } // Identificador único de la consulta
        public DateTime FechaCreacion { get; set; } // Fecha de creación de la consulta
        public string UsuarioCreacion { get; set; } // Usuario que crea la consulta
        public string HistorialConsulta { get; set; } // Historial médico del paciente
        public int? SecuencialConsulta { get; set; } // Número secuencial de la consulta
        public int PacienteId { get; set; } // Id del paciente relacionado
        public string MotivoConsulta { get; set; } // Motivo de la consulta
        public string EnfermedadConsulta { get; set; } // Descripción de la enfermedad
        public string NombrePariente { get; set; } // Nombre del pariente de contacto
        public string SignosAlarma { get; set; } // Signos de alarma que presenta el paciente
        public string ReconocimientoFarmacologico { get; set; } // Medicamentos conocidos o reconocidos
        public int TipoPariente { get; set; } // Tipo de pariente
        public string TelefonoPariente { get; set; } // Teléfono del pariente
        public string Temperatura { get; set; } // Temperatura del paciente
        public string FrecuenciaRespiratoria { get; set; } // Frecuencia respiratoria
        public string PresionArterialSistolica { get; set; } // Presión arterial sistólica
        public string PresionArterialDiastolica { get; set; } // Presión arterial diastólica
        public string Pulso { get; set; } // Pulso del paciente
        public string Peso { get; set; } // Peso del paciente
        public string Talla { get; set; } // Talla del paciente
        public string PlanTratamiento { get; set; } // Plan de tratamiento
        public string? Observacion { get; set; } // Observaciones generales de la consulta
        public string AntecedentesPersonales { get; set; } // Antecedentes personales del paciente
        public int DiasIncapacidad { get; set; } // Días de incapacidad
        public int MedicoId { get; set; } // Id del médico que realiza la consulta
        public int EspecialidadId { get; set; } // Id de la especialidad médica
        public int? TipoConsultaId { get; set; } = null; // Tipo de consulta
        public string NotasEvolucion { get; set; } // Notas de evolución del paciente
        public string ConsultaPrincipal { get; set; } // Consulta principal de la visita
        public int EstadoConsulta { get; set; } // Estado de la consulta

        // Relaciones con otras tablas
        public List<ConsultaAlergiaDTO> Alergias { get; set; } // Lista de alergias asociadas a la consulta
        public List<ConsultaCirugiaDTO> Cirugias { get; set; } // Lista de cirugías asociadas a la consulta
        public List<ConsultaMedicamentoDTO> Medicamentos { get; set; } // Lista de medicamentos asociados
        public List<ConsultaLaboratorioDTO> Laboratorios { get; set; } // Lista de laboratorios asociadosss
        public List<ConsultaImagenDTO> Imagenes { get; set; } // Lista de imágenes asociadas
        public List<ConsultaDiagnosticoDTO> Diagnosticos { get; set; } // Lista de diagnósticos asociados
        public OrganosSistema OrganosSistemas { get; set; } // Órganos y sistemas asociados
        public ExamenFisico ExamenFisico { get; set; } // Examen físico asociado
        public AntecedentesFamiliare AntecedentesFamiliares { get; set; } // Antecedentes familiares asociados

        public virtual Usuario? MedicoConsultaDNavigation { get; set; }
        public virtual Paciente? PacienteConsultaPNavigation { get; set; }
        public virtual Catalogo? EstadocivilPacientesCaNavigation { get; set; }
        public virtual Catalogo? FormacionprofesionalPacientesCaNavigation { get; set; }
        public virtual Pai? NacionalidadPacientesPaNavigation { get; set; }
        public virtual Localidad? ProvinciaPacientesLNavigation { get; set; }
        public virtual Catalogo? SegurosaludPacientesCaNavigation { get; set; }
        public virtual Catalogo? SexoPacientesCaNavigation { get; set; }
        public virtual Catalogo? TipodocumentoPacientesCaNavigation { get; set; }
        public virtual Catalogo? TiposangrePacientesCaNavigation { get; set; }


        // Constructor que inicializa los objetos complejos
        public Consultation()
        {
            AntecedentesFamiliares = new AntecedentesFamiliare();

            Alergias = new List<ConsultaAlergiaDTO>();
            Cirugias = new List<ConsultaCirugiaDTO>();
            Medicamentos = new List<ConsultaMedicamentoDTO>();
            Laboratorios = new List<ConsultaLaboratorioDTO>();
            Imagenes = new List<ConsultaImagenDTO>();
            Diagnosticos = new List<ConsultaDiagnosticoDTO>();
            OrganosSistemas = new OrganosSistema();
            ExamenFisico = new ExamenFisico();
   
        }
    }

    public class ConsultaAlergiaDTO
    {
        public int? CatalogoalergiaId { get; set; } // Solo envías el ID
        public string? ObservacionAlergias { get; set; }
        public int EstadoAlergias { get; set; } = 1; // Valor predeterminado
    }
    public class ConsultaCirugiaDTO
    {
        public int? CatalogocirugiaId { get; set; } // Solo envías el ID
        public string? ObservacionCirugia { get; set; }
        public int EstadoCirugias { get; set; } = 1; // Valor predeterminado
    }
    public class ConsultaImagenDTO
    {
        public int? ImagenId { get; set; }
        public string? ObservacionImagen { get; set; }

        public int? CantidadImagen { get; set; }
        public int? SecuencialImagen { get; set; }

        public int EstadoImagen { get; set; }
    }
    public class ConsultaLaboratorioDTO
    {
        public int? CatalogoLaboratorioId { get; set; }
       
        public int? CantidadLaboratorio { get; set; }
        public string? Observacion { get; set; }
        public int? SecuencialLaboratorio { get; set; }

        public int EstadoLaboratorio { get; set; }
    }
    public class ConsultaMedicamentoDTO
    {
        public int? MedicamentoId { get; set; }
        public string? DosisMedicamento { get; set; }
        public string? ObservacionMedicamento { get; set; }
        public int? SecuencialMedicamento { get; set; }

        public int EstadoMedicamento { get; set; }
    }

    public class ConsultaDiagnosticoDTO
    {
        public int? DiagnosticoId { get; set; }
        public string? ObservacionDiagnostico { get; set; }
        public bool? PresuntivoDiagnosticos { get; set; }
        public bool? DefinitivoDiagnosticos { get; set; }
        public int? SecuencialDiagnostico { get; set; }

        public int EstadoDiagnostico { get; set; }
    }

}

MedicExpermed/Controllers/ConsultationController.cs
using MedicExpermed.Models;
using MedicExpermed.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Data;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using QuestPDF.Previewer;
using System.Globalization;


namespace MedicExpermed.Controllers
{
    public class ConsultationController : Controller
    {
        private readonly AppointmentService _citaService;
        private readonly PatientService _patientService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ConsultationService _consultationService;
        private readonly CatalogService _catalogService;
        private readonly ILogger<ConsultationController> _logger;
        private readonly medicossystembdIContext _medical_SystemContext;

        public ConsultationController(AppointmentService citaService, PatientService patientService, IHttpContextAccessor httpContextAccessor, ConsultationService consultationService, CatalogService catalogService, ILogger<ConsultationController> logger, medicossystembdIContext medical_SystemContext)
        {
            _citaService = citaService;
            _patientService = patientService;
            _httpContextAccessor = httpContextAccessor;
            _consultationService = consultationService;
            _catalogService = catalogService;
            _logger = logger;
            _medical_SystemContext = medical_SystemContext;
        }



        private async Task CargarListasDesplegables()
        {
            ViewBag.TiposDocumentos = await _catalogService.ObtenerTiposDocumentoAsync();
            ViewBag.TiposSangre = await _catalogService.ObtenerTiposSangreAsync();
            ViewBag.TiposGenero = await _catalogService.ObtenerTiposGeneroAsync();
            ViewBag.TiposEstadoCivil = await _catalogService.ObtenerTiposEstadoCivilAsync();
            ViewBag.TiposFormacion = await _catalogService.ObtenerTiposFormacionAsync();
            ViewBag.TiposNacionalidad = await _catalogService.ObtenerTiposDeNacionalidadPAsync();
            ViewBag.TiposProvincia = await _catalogService.ObtenerTiposDeProvinciaPAsync();
            ViewBag.TiposSeguro = await _catalogService.ObtenerTiposSeguroSaludAsync();
            ViewBag.TiposPariente = await _catalogService.ObtenerTiposParentescoAsync();
            ViewBag.TiposAlergias = await _catalogService.ObtenerAlergiasAsync();
            ViewBag.TiposCirugias = await _catalogService.ObtenerCirugiasAsync();
            ViewBag.TiposParienteAntece = await _catalogService.ObtenerAntecedentesFAsync();
            ViewBag.TiposMedicamentos = await _catalogService.ObtenerMedicamentosActivasAsync();
            ViewBag.TiposLaboratorios = await _catalogService.ObtenerLaboratorioActivasAsync();
            ViewBag.TiposImagen = await _catalogService.ObtenerImagenActivasAsync();
            ViewBag.TiposDiagnostico = await _catalogService.ObtenerDiagnosticosActivasAsync();
        }

        [HttpGet("Listar-Consultas")]
        public async Task<IActionResult> ListarConsultas()
        {
            try
            {
                var consultas = await _consultationService.GetAllConsultasAsync();
                ViewBag.UsuarioEspecialidad = HttpContext.Session.GetString("UsuarioEspecialidad");

                return View(consultas);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(new List<Consultum>());
            }
        }

        [HttpGet("Crear-Consulta")]
        public async Task<IActionResult> CrearConsulta()
        {
            // Obtener IDs de "NINGUNA"
            int ningunTipoParienteId = await _catalogService.ObtenerIdParentescoNingunoAsync();
            int ningunAlergiasId = await _catalogService.ObtenerIdAlergiasNingunoAsync();

            // Crear una nueva instancia de Consultation
            var consulta = new Consultation
            {
                TipoPariente = ningunTipoParienteId,
                FechaCreacion = DateTime.Now
            };

            // Añadir el ID "NINGUNA" a la lista de alergias
            consulta.Alergias.Add(new ConsultaAlergiaDTO
            {
                CatalogoalergiaId = ningunAlergiasId,
                ObservacionAlergias = "Ninguna alergia registrada",
                EstadoAlergias = 1
            });

            // Asignar datos a ViewBag desde la sesión
            ViewBag.UsuarioNombre = HttpContext.Session.GetString("UsuarioNombre");
            ViewBag.UsuarioId = HttpContext.Session.GetInt32("UsuarioId");
            ViewBag.UsuarioIdEspecialidad = HttpContext.Session.GetInt32("UsuarioIdEspecialidad");

            // Cargar listas desplegables
            await CargarListasDesplegables();

            // Devolver el modelo a la vista
            return View(consulta);
        }


        [HttpPost("Crear-Consulta")]
        public async Task<IActionResult> CrearConsulta([FromBody] Consultation consultaDto)
        {
            if (!ModelState.IsValid)
            {
                var errores = ModelState
                    .Where(x => x.Value.Errors.Count > 0)
                    .Select(x => new { Field = x.Key, Errors = x.Value.Errors.Select(e => e.ErrorMessage) })
                    .ToList();

                foreach (var error in errores)
                {
                    Console.WriteLine($"Campo: {error.Field}, Errores: {string.Join(", ", error.Errors)}");
                }

                return Json(new { success = false, errores });
            }



            try
            {
                // Llama al servicio para crear la consulta
                await _consultationService.CrearConsultaAsync(
                    consultaDto.UsuarioCreacion,
                    consultaDto.HistorialConsulta,
                    consultaDto.PacienteId,
                    consultaDto.MotivoConsulta,
                    consultaDto.EnfermedadConsulta,
                    consultaDto.NombrePariente,
                    consultaDto.SignosAlarma,
                    consultaDto.ReconocimientoFarmacologico,
                    consultaDto.TipoPariente,
                    consultaDto.TelefonoPariente,
                    consultaDto.Temperatura,
                    consultaDto.FrecuenciaRespiratoria,
                    consultaDto.PresionArterialSistolica,
                    consultaDto.PresionArterialDiastolica,
                    consultaDto.Pulso,
                    consultaDto.Peso,
                    consultaDto.Talla,
                    consultaDto.PlanTratamiento,
                    consultaDto.Observacion,
                    consultaDto.AntecedentesPersonales,
                    consultaDto.DiasIncapacidad,
                    consultaDto.MedicoId,
                    consultaDto.EspecialidadId,
                    consultaDto.TipoConsultaId ?? 0,
                    consultaDto.NotasEvolucion,
                    consultaDto.ConsultaPrincipal,
                    consultaDto.EstadoConsulta,
                    // Parámetros de órganos y sistemas
                    consultaDto.OrganosSistemas.OrgSentidos,
                    consultaDto.OrganosSistemas.ObserOrgSentidos,
                    consultaDto.OrganosSistemas.Respiratorio,
                    consultaDto.OrganosSistemas.ObserRespiratorio,
                    consultaDto.OrganosSistemas.CardioVascular,
                    consultaDto.OrganosSistemas.ObserCardioVascular,
                    consultaDto.OrganosSistemas.Digestivo,
                    consultaDto.OrganosSistemas.ObserDigestivo,
                    consultaDto.OrganosSistemas.Genital,
                    consultaDto.OrganosSistemas.ObserGenital,
                    consultaDto.OrganosSistemas.Urinario,
                    consultaDto.OrganosSistemas.ObserUrinario,
                    consultaDto.OrganosSistemas.MEsqueletico,
                    consultaDto.OrganosSistemas.ObserMEsqueletico,
                    consultaDto.OrganosSistemas.Endocrino,
                    consultaDto.OrganosSistemas.ObserEndocrino,
                    consultaDto.OrganosSistemas.Linfatico,
                    consultaDto.OrganosSistemas.ObserLinfatico,
                    consultaDto.OrganosSistemas.Nervioso,
                    consultaDto.OrganosSistemas.ObserNervioso,
                    // Parámetros de examen físico
                    consultaDto.ExamenFisico.Cabeza,
                    consultaDto.ExamenFisico.ObserCabeza,
                    consultaDto.ExamenFisico.Cuello,
                    consultaDto.ExamenFisico.ObserCuello,
                    consultaDto.ExamenFisico.Torax,
                    consultaDto.ExamenFisico.ObserTorax,
                    consultaDto.ExamenFisico.Abdomen,
                    consultaDto.ExamenFisico.ObserAbdomen,
                    consultaDto.ExamenFisico.Pelvis,
                    consultaDto.ExamenFisico.ObserPelvis,
                    consultaDto.ExamenFisico.Extremidades,
                    consultaDto.ExamenFisico.ObserExtremidades,
                    // Parámetros de antecedentes familiares
                    consultaDto.AntecedentesFamiliares.Cardiopatia,
                    consultaDto.AntecedentesFamiliares.ObserCardiopatia,
                    consultaDto.AntecedentesFamiliares.ParentescocatalogoCardiopatia,
                    consultaDto.AntecedentesFamiliares.Diabetes,
                    consultaDto.AntecedentesFamiliares.ObserDiabetes,
                    consultaDto.AntecedentesFamiliares.ParentescocatalogoDiabetes,
                    consultaDto.AntecedentesFamiliares.EnfCardiovascular,
                    consultaDto.AntecedentesFamiliares.ObserEnfCardiovascular,
                    consultaDto.AntecedentesFamiliares.ParentescocatalogoEnfcardiovascular,

MedicExpermed/Views/Consultation/ListarConsultas.cshtml
@model List<Consultum>

@{
    ViewData["Title"] = "Listar Consultas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Lista de consultas</h1>

@if (ViewBag.Error != null)
{
    <div class="alert alert-danger">@ViewBag.Error</div>
}

<div class="form-group">
    <div class="row">
        <div class="col-md-3">
            <label for="opcionConsultas">Buscar por</label>
            <select class="form-control" id="opcionConsultas">
                <option value="-2">Listar todo</option>
                <option value="1">Nombre(s)</option>
                <option value="2">Número de documento</option>
                <option value="3">Especialidad</option>
                <option value="4">Motivo</option>
            </select>
        </div>
        <div class="col-md-5 d-none" id="buscarFieldsConsultas">
            <label>&nbsp;</label>
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Ingresar criterio de búsqueda" id="buscarCriterioConsultas" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button" onclick="onSearch('consultas')">Buscar</button>
                </div>
            </div>
        </div>
    </div>
</div>
<hr />

<div class="table-responsive d-none d-lg-block">
    <table class="table table-bordered table-striped">
        <thead>
            <tr class="table-primary">
                <th>Acciones</th>
                <th data-search-type="1">Fecha de la consulta</th>
                <th data-search-type="2">Nombre Paciente</th>
                <th data-search-type="3">Especialidad</th>
                <th data-search-type="4">Motivo</th>
                <th>Enfermedad</th>
                <th>Historial</th>
                <th>Estado</th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Count > 0)
            {
                @foreach (var consulta in Model)
                {
                    <tr id="consulta-@consulta.IdConsulta" data-type="consultas">
                        <td>
                            <a asp-action="VerConsulta" asp-route-id="@consulta.IdConsulta" class="btn btn-outline-success">
                                <i class="fa-regular fa-eye"></i> Visualizar
                            </a>
                        </td>
                        <td data-search-type="1">@consulta.FechacreacionConsulta</td>
                        <td data-search-type="2">@consulta.PacienteConsultaPNavigation?.PrimernombrePacientes @consulta.PacienteConsultaPNavigation?.PrimerapellidoPacientes</td>
                        <td data-search-type="3">@ViewBag.UsuarioEspecialidad</td>
                        <td data-search-type="4">@consulta.MotivoConsulta</td>
                        <td>@consulta.EnfermedadConsulta</td>
                        <td>@consulta.HistorialConsulta</td>
                        <td>@consulta.EstadoConsultaC</td>
                    </tr>
                }
            }
            else
            {
                <tr>
                    <td colspan="8" class="text-center">No se encontraron consultas.</td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div class="card-columns d-lg-none">
    @foreach (var consulta in Model)
    {
        <div class="card" data-type="consultas">
            <div class="card-body" data-id="@consulta.IdConsulta">
                <h5 class="card-title" data-search-type="2">@consulta.PacienteConsultaPNavigation?.PrimernombrePacientes @consulta.PacienteConsultaPNavigation?.PrimerapellidoPacientes</h5>
                <p class="card-text" data-search-type="1"><strong>Fecha de la consulta:</strong> @consulta.FechacreacionConsulta</p>
                <p class="card-text" data-search-type="3"><strong>Especialidad:</strong> @ViewBag.UsuarioEspecialidad</p>
                <p class="card-text" data-search-type="4"><strong>Motivo:</strong> @consulta.MotivoConsulta</p>
                <p class="card-text"><strong>Enfermedad:</strong> @consulta.EnfermedadConsulta</p>
                <p class="card-text"><strong>Historial:</strong> @consulta.HistorialConsulta</p>
                <p class="card-text"><strong>Estado:</strong> @consulta.EstadoConsultaC</p>
                <a asp-action="VerConsulta" asp-route-id="@consulta.IdConsulta" class="btn btn-outline-success btn-sm">
                    <i class="fa-regular fa-eye"></i> Visualizar
                </a>
            </div>
        </div>
    }
</div>

<div id="noResultsConsultas" class="no-results d-none">
    No se encontraron resultados.
</div>

<a asp-action="CrearConsulta" asp-controller="Consultation" class="btn btn-outline-primary" style="margin-left:80%">
    <i class="fa fa-plus"></i> Añadir nueva consulta
</a>

@section Scripts {
    <script src="~/js/searchConsultationFunctions.js"></script>
    <script>

        // Mostrar mensajes de éxito o error
        var successMessage = '@TempData["SuccessMessage"]';
        var errorMessage = '@TempData["ErrorMessage"]';

        if (successMessage) {
            Swal.fire({
                icon: 'success',
                title: 'Éxito',
                text: successMessage
            });
        }

        if (errorMessage) {
            Swal.fire({
                icon: 'error',
                title: 'Error',
                text: errorMessage
            });
        }
    </script>
}